version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "81:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/html:/usr/share/nginx/html"
    restart: always